pipeline {
    agent any

    environment {
        SONAR_SCANNER_HOME = tool 'sonar'  // Usa el nombre configurado en Jenkins
        SONAR_HOST_URL = 'http://172.30.227.110:9000'   // Cambia por la URL de tu SonarQube
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/luimungar3/tienda.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonar1', variable: 'sonar')]) {
                    sh """
                        ${SONAR_SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.projectKey=tienda \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://172.30.227.110:9000/ \
                        -Dsonar.login=${sonar1}
                    """
                    }
            }
        }

        stage('Quality Gate') {
            steps {
                script {
                    timeout(time: 5, unit: 'MINUTES') {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Quality Gate failed: ${qg.status}"
                        }
                    }
                }
            }
        }
    }
}
