pipeline {
    agent any

    environment {
        SONAR_HOST_URL = 'http://192.168.1.89:9000/'   // Cambia por la URL de tu SonarQube
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/luimungar3/tienda.git'
            }
        }

       stage('SonarQube Analysis') {
            steps {
        withSonarQubeEnv('sonar') {
            tool name: 'SonarQube_Scanner', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
            withCredentials([string(credentialsId: 'sonar1', variable: 'sonar')]) {
                sh """
                    sonar-scanner \
                    -Dsonar.projectKey=tienda \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=http://192.168.1.89:9000/ \
                    -Dsonar.login=${sonar}
                """
                    }
                }
            }
        }


        stage('Quality Gate') {
            steps {
                script {
                    timeout(time: 5, unit: 'MINUTES') {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Quality Gate failed: ${qg.status}"
                        }
                    }
                }
            }
        }
    }
}
